server:
  http_listen_port: 19080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: lammps-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: lammps-api
          __path__: /var/log/lammps/api.log

  - job_name: lammps-worker
    static_configs:
      - targets:
          - localhost
        labels:
          job: lammps-worker
          __path__: /var/log/lammps/worker.log

  - job_name: lammps-celery
    static_configs:
      - targets:
          - localhost
        labels:
          job: lammps-celery
          __path__: /var/log/lammps/celery.log

  - job_name: lammps-lammps
    static_configs:
      - targets:
          - localhost
        labels:
          job: lammps-simulation
          __path__: /var/log/lammps/lammps_*.log

  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log
